---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt::default]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  run_list:
  - recipe[yum::epel]
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

busser:
  sudo: true

suites:
# This test sets up a simple PHP application, verifies the functionality of the application, and ensures that
# the required application packages are installed.
#
- name: default
  run_list:
  - recipe[rs-application_php::default]
  - recipe[rs-application_php::tags]
  - recipe[rs-application_php::monitoring]
  - recipe[curl::default]
  attributes:
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.10']
      private_ips: ['10.0.2.15']
    rs-application_php:
      packages: ['sl']
      application_name: example
      migration_command: echo migration is being performed >> /usr/local/www/sites/example/migration
      scm:
        revision: unified_php
        repository: git://github.com/rightscale/examples.git

# This test sets up a mysql database server locally, tests the database connectivity from the application to the
# database server, and ensures that the required database client packages are installed.
#
- name: database_mysql
  run_list:
  - recipe[mysql::server]
  - recipe[fake::database_mysql]
  - recipe[rs-application_php::default]
  - recipe[curl::default]
  attributes:
    cloud:
      provider: vagrant
      private_ips: ['10.0.0.2']
    # The mysql cookbook requires these attributes to be set for running mysql server in a
    # vagrant environment
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.10']
      private_ips: ['10.0.2.15']
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
    rs-application_php:
      application_name: example
      scm:
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        host: localhost
        user: app_user
        password: apppass
        schema: app_test
