---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: centos-6.5
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: opscode-centos-6.5
- name: rhel-6.5
  run_list: ['recipe[yum-epel]', 'recipe[rhsm::register]']
  attributes:
    rhsm:
      username: <%= ENV['RHSM_USERNAME'] %>
      password: <%= ENV['RHSM_PASSWORD'] %>
      additional_repos: ['rhel-6-server-optional-rpms']
  driver_config:
    box: local-rhel-6.5
    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-6.5_chef-provisionerless.box
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  attributes:
    apt:
      compile_time_update: true
  driver_config:
    box: opscode-ubuntu-12.04
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  attributes:
    apt:
      compile_time_update: true
  driver_config:
    box: opscode-ubuntu-14.04

busser:
  sudo: true

suites:
# This test sets up a simple PHP application, verifies the functionality of the application, and ensures that
# the required application packages are installed.
#
- name: default
  run_list:
  - recipe[rs-application_php::default]
  - recipe[rs-application_php::tags]
  - recipe[rs-application_php::collectd]
  - recipe[curl::default]
  attributes:
    rightscale:
      instance_uuid: '01-ABCDEFGH0123'
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.10']
      private_ips: ['10.0.2.15']
    rs-application_php:
      packages: ['sl']
      application_name: example
      vhost_path: www.example.com
      bind_network_interface: 'public'
      migration_command: echo migration is being performed >> /usr/local/www/sites/example/migration
      scm:
        revision: unified_php
        repository: git://github.com/rightscale/examples.git

# This test sets up a mysql database server locally, tests the database connectivity from the application to the
# database server, and ensures that the required database client packages are installed.
#
- name: database_mysql
  run_list:
  - recipe[mysql::server]
  - recipe[fake::database_mysql]
  - recipe[rs-application_php::default]
  - recipe[curl::default]
  attributes:
    # The mysql cookbook requires these attributes to be set for running mysql server in a
    # vagrant environment
    cloud:
      provider: vagrant
      public_ips: ['33.33.33.10']
      private_ips: ['10.0.2.15']
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
    rs-application_php:
      application_name: example
      scm:
        revision: unified_php
        repository: git://github.com/rightscale/examples.git
      database:
        host: localhost
        user: app_user
        password: apppass
        schema: app_test
