language: ruby
rvm:
- 2.3.1
before_install:
- curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.2.22
install:
- chef exec bundle install --jobs=3 --retry=3
before_script: chef exec rake setup_test_environment
script: "./.travis_install.sh"
notifications:
  slack:
    secure: JQYkoAiYhzU29x90aOFPb5+mBY0DEYLLilIWY67bqJGYz0NeyVJMZVDq5FyBq0ERroCZ553Ve1Yl9SCgP28klluFHFRX4/2Hz7voVNt11zG2cMnRTXIFESepmJAjMa6tFGwuXdPSvRzl/DV56kqkA8vB0Gr0M+kQuqKxEG7r/AQ=
