#
# Cookbook Name:: rs-application_php
# Attribute:: default
#
# Copyright (C) 2013 RightScale, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Packages to install
default['rs-application_php']['packages'] = []

# PHP PEAR packages to install
default['rs-application_php']['pear_packages'] = []

# Application listen port
default['rs-application_php']['listen_port'] = 8080

# The source control provider
default['rs-application_php']['scm']['provider'] = 'git'

# The repository to checkout the code from
default['rs-application_php']['scm']['repository'] = nil

# The revision of application code to checkout from the repository
default['rs-application_php']['scm']['revision'] = nil

# The name of the application
default['rs-application_php']['application_name'] = nil

# The root of the application
default['rs-application_php']['app_root'] = '/'

# The command used to perform application migration
default['rs-application_php']['migration_command'] = nil

# Whether to crete the local settings file on the application deployment
default['rs-application_php']['write_settings_file'] = true

# The name of the local settings file to be generated by a template
default['rs-application_php']['local_settings_file'] = 'LocalSettings.php'

# The name of the template that will be rendered to create the local settings file
default['rs-application_php']['settings_template'] = nil

# Database configuration

# The database provider
default['rs-application_php']['database']['provider'] = 'mysql'

# The database host
default['rs-application_php']['database']['host'] = 'localhost'

# The database username
default['rs-application_php']['database']['user'] = nil

# The database password
default['rs-application_php']['database']['password'] = nil

# The database schema name
default['rs-application_php']['database']['schema'] = nil

# Application callback attributes.
#
# These attributes are interpreted as callback to be called at specific points during
# a deployment. If a block is passed, it will be evaluated within the new context. If a string is passed, it will be
# interpreted as a path (relative to the release directory) to a file; if the file exists, it will be loaded and
# evaluated as though it were a Chef recipe.
#

# Callback that is invoked immediately after initial setup and before the deployment is started. This callback will be
# invoked on every Chef run.
#
default['rs-application_php']['before_deploy'] = nil

# Callback that is invoked before the migration is started
default['rs-application_php']['before_migrate'] = nil

# Callback that is invoked before the symlinks are created
default['rs-application_php']['before_symlink'] = nil

# Callback that is invoked before the application is restarted
default['rs-application_php']['before_restart'] = nil

# Callback that is invoked after the application is restarted
default['rs-application_php']['after_restart'] = nil
